server:
  port: 8080
management:
  server:
    port: 54001
  health:
    mail:
      enabled: false
info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    spring-boot-version: '@project.parent.version@'
spring:
  redis:
    password: Redis!123
    port: 6379
    host: 127.0.0.1
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/kuangchi
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql